apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: cheese-java-pipeline-01
        app.kubernetes.io/component: cheese-java-pipeline-01
        app.kubernetes.io/instance: cheese-java-pipeline-01
      name: cheese-java-pipeline-01-deploy
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: cheese-java-pipeline-01
      template:
        metadata:
          labels:
            app: cheese-java-pipeline-01
          name: cheese-java-pipeline-01
        spec:
          containers:
            - image: docker.io/m1k3pjem/hello-java-spring-boot:latest
              imagePullPolicy: IfNotPresent
              name: hello-java-spring-boot
              env:
                - name: FAVOURITE_CHEESE
                  valueFrom:
                    configMapKeyRef:
                      name: hello-java-spring-boot-configmap
                      key: thefavourite.cheese
              ports:
                - containerPort: 8080
                  protocol: TCP
          restartPolicy: Always
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: cheese-java-pipeline-01
        app.kubernetes.io/component: cheese-java-pipeline-01
        app.kubernetes.io/instance: cheese-java-pipeline-01
      name: cheese-java-pipeline-01-service
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deployment: cheese-java-pipeline-01
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      labels:
          app: cheese-java-pipeline-01
          app.kubernetes.io/component: cheese-java-pipeline-01
          app.kubernetes.io/instance: cheese-java-pipeline-01
      name: hello-java-spring-boot-configmap
    data:
      thefavourite.cheese: GOUDA
