apiVersion: v1
kind: Template
metadata:
  name: ${APP_NAME}
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}-is
    labels:
      app: ${LABEL}
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: ${APP_NAME}-bc
    labels:
      app: ${LABEL}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: hello-java-spring-boot:latest
    postCommit: {}
    resources: {}
    source:
      type: Binary
      binary: {}
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: 'hello-java-spring-boot:latest'
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
    runPolicy: Serial
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ${APP_NAME}
      app.kubernetes.io/component: ${APP_NAME}
      app.kubernetes.io/instance: ${APP_NAME}
    name: ${APP_NAME}-deploy
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${APP_NAME}
    template:
      metadata:
        labels:
          app: ${LABEL}
        name: ${APP_NAME}
      spec:
        containers:
          - image: docker.io/m1k3pjem/hello-java-spring-boot:latest
            imagePullPolicy: IfNotPresent
            name: hello-java-spring-boot
            env:
              - name: FAVOURITE_CHEESE
                valueFrom:
                  configMapKeyRef:
                    name: hello-java-spring-boot-configmap
                    key: thefavourite.cheese
            ports:
              - containerPort: 8080
                protocol: TCP
        restartPolicy: Always
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${LABEL}
      app.kubernetes.io/component: ${APP_NAME}
      app.kubernetes.io/instance: ${APP_NAME}
    name: ${APP_NAME}-service
  spec:
    ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: ${LABEL}
      deployment: ${APP_NAME}-deploy
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${APP_NAME}-route
    labels:
      app: ${LABEL}
  spec:
    host: ${APP_NAME}-${OPENSHIFT_PROJECT}.${OPENSHIFT_CLUSTER_DOMAIN}
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ${APP_NAME}-service
      weight: 100
    wildcardPolicy: None
parameters:
  - name: GITHUB_BRANCH
    required: true
    value: main
  - name: APP_NAME 
    required: true
    value: cheese-java-pipeline-01
  - name: LABEL 
    required: true
    value: cheese-java-pipeline-01
  - name: OPENSHIFT_PROJECT
    required: true
  - name: OPENSHIFT_CLUSTER_DOMAIN 
    required: true
