apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: cheese-java-pipeline-01
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: cheese-java-pipeline-01-is
    labels:
      app: cheese-java-pipeline-01
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: cheese-java-pipeline-01-bc
    labels:
      app: cheese-java-pipeline-01
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: hello-java-spring-boot:latest
    postCommit: {}
    resources: {}
    source:
      type: Binary
      binary: {}
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: 'hello-java-spring-boot:latest'
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
    runPolicy: Serial
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: cheese-java-pipeline-01
      app.kubernetes.io/component: cheese-java-pipeline-01
      app.kubernetes.io/instance: cheese-java-pipeline-01
    name: cheese-java-pipeline-01-deploy
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: cheese-java-pipeline-01
    template:
      metadata:
        labels:
          app: cheese-java-pipeline-01
        name: cheese-java-pipeline-01
      spec:
        containers:
          - image: docker.io/m1k3pjem/hello-java-spring-boot:latest
            imagePullPolicy: IfNotPresent
            name: hello-java-spring-boot
            env:
              - name: FAVOURITE_CHEESE
                valueFrom:
                  configMapKeyRef:
                    name: hello-java-spring-boot-configmap
                    key: thefavourite.cheese
            ports:
              - containerPort: 8080
                protocol: TCP
        restartPolicy: Always
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: cheese-java-pipeline-01
      app.kubernetes.io/component: cheese-java-pipeline-01
      app.kubernetes.io/instance: cheese-java-pipeline-01
    name: cheese-java-pipeline-01-service
  spec:
    ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      app: cheese-java-pipeline-01
      deployment: cheese-java-pipeline-01-deploy
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: cheese-java-pipeline-01-route
    labels:
      app: cheese-java-pipeline-01
  spec:
    host: ${APP_NAME}-${OPENSHIFT_PROJECT}.${OPENSHIFT_CLUSTER_DOMAIN}
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: cheese-java-pipeline-01-service
      weight: 100
    wildcardPolicy: None
parameters:
  - name: GITHUB_BRANCH
    required: true
    value: main
  - name: OPENSHIFT_PROJECT
    required: true
  - name: OPENSHIFT_CLUSTER_DOMAIN 
    required: true
