apiVersion: v1
kind: Template
metadata:
  name: ${APP_NAME}
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${LABEL}
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${LABEL}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: /
      git:
        uri: https://github.com/m1k3dcdc/cheese-java-pipeline-01
        ref: main
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: Dockerfile
    triggers:
    - type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: apps.openshift.io/v1
  kind: Deployment
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${LABEL}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${LABEL}
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: ${LABEL}
          deployment: ${APP_NAME}
      spec:
        containers:
        - name: ${APP_NAME}
          image: ${APP_NAME}:latest
          env:
            - name: TIMEOUT
              value: ${TIMEOUT}
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          ports:
          - containerPort: 8080
            protocol: TCP
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - windfire-restaurants-backend
        from:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${LABEL}
  spec:
    ports:
    - name: 8080tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${LABEL}
      deploymentconfig: ${APP_NAME}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${LABEL}
  spec:
    host: ${APP_NAME}
    port:
      targetPort: 8080tcp
    to:
      kind: Service
      name: ${APP_NAME}
      weight: 100
    wildcardPolicy: None
parameters:
  - name: GITHUB_BRANCH
    required: true
    value: main
  - name: APP_NAME 
    required: true
    value: cheese-java-pipeline
  - name: LABEL 
    required: true
    value: cheese-java-pipeline
  - name: TIMEOUT
    required: true
    value: 5000
